name: Auto-release

# Triggers the workflow on midnight
#on:
#  schedule:
#    - cron: '0 3 * * *'
on:
  push:
    branches: [ onPush ]

jobs:
  auto-release:
    # Run job on a basic ubuntu machine
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: develop

      # Install dependencies
      - name: Installing Dependencies
        run: npm install

      - name: Install deployer
        run: npm install
        working-directory: scripts

      - name: Run deploy
        run: npm run autoRelease
        working-directory: scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
