name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    # Run job on a basic ubuntu machine
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: develop

      # Install dependencies
      - name: CI
        run: echo "hola :)"
