name: Deploy

# Triggers the workflow on push or pull request events but only for the develop branch
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[deploy]')
    # Run job on a basic ubuntu machine
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Installing Dependencies
        run: npm install

      - name: Install deployer
        run: npm install
        working-directory: scripts

      - name: Deploy to AWS
        run: echo "deploy AWS"
      
      - name: Run deploy
        run: npm run deploy
        working-directory: scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
